name: test-pipeline

on:
  push:
    branches:
      - main
  pull_request:

env:
  NXF_ANSI_LOG: false

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  nextflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: setup-nextflow
        uses: nf-core/setup-nextflow@b9f764e8ba5c76b712ace14ecbfcef0e40ae2dd8 # v1.5.2

      - name: run-nextflow
        run: nextflow run . -profile my_laptop,demo -c .github/workflows/nextflow.config
